name: Deploy PR previews
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Node.js
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        if: github.event.action != 'closed'
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: pnpm install

      - name: Build
        if: github.event.action != 'closed'
        uses: withastro/action@v3
        with:
          path: .
          node-version: 20
          package-manager: pnpm@latest

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          umbrella-dir: pr-preview
          action: ${{ github.event.action }}
